services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: alumnos_db
      MYSQL_USER: admin_alumnos
      MYSQL_PASSWORD: password_alumnos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: ./back-end
    container_name: django_app
    command: >
      sh -c "python3 manage.py makemigrations && 
             python3 manage.py migrate && 
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./back-end/alumnos:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  ionic-app:
    build: ./front-end/miAppAlumnos
    ports:
      - "8100:80"
    container_name: ionic-app

volumes:
  mysql_data: