version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: alumnos_db
      MYSQL_USER: admin_alumnos
      MYSQL_PASSWORD: password_alumnos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: .
    container_name: django_app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./alumnos:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data: